# Generated by Django 2.0.5 on 2018-05-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('ADAS', 'ADAS'), ('BIW', 'BIW'), ('Chassis', 'Chassis'), ('Exterior', 'Exterior'), ('Interior', 'Interior'), ('Powertrain', 'Powertrain'), ('Thermal', 'Thermal'), ('LowVoltageEE', 'LowVoltage EE'), ('Connectivity', 'Connectivity'), ('ICE', 'Intelligent Car Experience')], default='ADAS', max_length=30)),
                ('commodity', models.CharField(default='e.g. Radar', max_length=200)),
                ('audit_before', models.DateField(auto_now=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=30)),
                ('supplier_name', models.CharField(max_length=30)),
                ('supplier_location', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(max_length=254)),
                ('buyer_first_name', models.CharField(max_length=30)),
                ('buyer_last_name', models.CharField(max_length=30)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('quality_first_name', models.CharField(max_length=30)),
                ('quality_last_name', models.CharField(max_length=30)),
                ('quality_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
