# Generated by Django 2.0.5 on 2018-05-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='audit_text',
            new_name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='audit',
            name='request_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='system_name',
            field=models.CharField(default='powertrain', max_length=200),
        ),
    ]
