# Generated by Django 2.0.5 on 2018-05-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auto_20180523_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='commodity_name',
            field=models.CharField(default='ex. powertrain', max_length=200),
        ),
        migrations.AddField(
            model_name='audit',
            name='supplier_contact',
            field=models.CharField(default='supplier contact', max_length=200),
        ),
        migrations.AddField(
            model_name='audit',
            name='supplier_location',
            field=models.CharField(default='supplier location', max_length=200),
        ),
        migrations.AlterField(
            model_name='audit',
            name='supplier_name',
            field=models.CharField(max_length=200, verbose_name='supplier name'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='system_name',
            field=models.CharField(default='ex. powertrain', max_length=200),
        ),
    ]
