# Generated by Django 2.0.5 on 2018-05-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auto_20180523_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='commodity_name',
            new_name='commodity',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='supplier_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='supplier_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='supplier_name',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='system_name',
        ),
    ]
